# name: Deploy to Firebase Hosting on push to the master branch

# on:
#   push:
#     branches:
#       - master

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Cache node modules
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.npm
#             ./node_modules
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
#       - name: Install Dependencies
#         run: npm ci
#       - name: Cache node modules after install
#         uses: actions/cache@v4
#         with:
#           path: ./node_modules
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#   build:
#     runs-on: ubuntu-latest
#     needs: ci
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Restore node modules cache
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.npm
#             ./node_modules
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
#       - name: Build
#         run: npm run build
#       - name: Upload dist folder
#         uses: actions/upload-artifact@v4
#         with:
#           name: dist-folder
#           path: dist/

#   prod:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Restore node modules cache
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.npm
#             ./node_modules
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
#       - name: Download dist folder
#         uses: actions/download-artifact@v4
#         with:
#           name: dist-folder
#           path: dist/
#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0.9.0
#         with:
#           repoToken: ${{ secrets.GITHUB_TOKEN }}
#           firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOUR_FIREBASE_PROJECT_ID }}
#           channelId: live
#           projectId: YOUR_FIREBASE_PROJECT_ID
